'use client';

import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import StormChart from './Chart';
import { storms, type Storm, type TrackPoint } from './data';

type Metric = 'wind'|'pressure'|'rain';
type Observation = { hour:number; lat:number; lon:number; wind:number; pressure:number; rain:number };

const EMPTY: Observation = {hour:0,lat:18.2,lon:132.4,wind:45,pressure:996,rain:110};

function csvCells(line:string){const out:string[]= [];let cell='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){out.push(cell.trim());cell=''}else cell+=c}out.push(cell.trim());return out}
function n(value:unknown,fallback=0){const parsed=Number(value);return Number.isFinite(parsed)?parsed:fallback}
function normalizeRow(raw:Record<string,unknown>,i:number):TrackPoint|null{
  const lower=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k.toLowerCase().trim(),v]));
  const lat=n(lower.lat??lower.latitude,NaN),lon=n(lower.lon??lower.longitude,NaN),wind=n(lower.wind??lower.wind_kt??lower.max_wind_kt,NaN),pressure=n(lower.pressure??lower.pressure_hpa??lower.min_pressure_hpa,NaN);
  if(![lat,lon,wind,pressure].every(Number.isFinite)||lat < -90||lat > 90||lon < -180||lon > 360||wind<0||pressure<800||pressure>1050)return null;
  return {hour:n(lower.hour??lower.forecast_hour,i*6),lat,lon,wind,rain:n(lower.rain??lower.rain_mm,0),pressure};
}
function importedStorm(name:string,track:TrackPoint[]):Storm{
  const maxWind=Math.round(Math.max(...track.map(p=>p.wind))),minPressure=Math.round(Math.min(...track.map(p=>p.pressure)));
  return{id:`import-${Date.now()}`,name:name.replace(/\.[^.]+$/,'').toUpperCase().slice(0,18)||'IMPORTED',year:new Date().getFullYear(),basin:'LOCAL DATASET',category:maxWind>=137?'CATEGORY 5':maxWind>=113?'CATEGORY 4':maxWind>=96?'CATEGORY 3':maxWind>=83?'CATEGORY 2':maxWind>=64?'CATEGORY 1':'TROPICAL STORM',maxWind,minPressure,movement:'USER DATA',radius:Math.round(65+maxWind*.7),landfall:'IMPORTED OBSERVATIONS',color:'#0085ca',track:track.sort((a,b)=>a.hour-b.hour)};
}

export default function DataWorkbench({initialStorm}:{initialStorm:Storm}){
  const [saved,setSaved]=useState<Storm[]>([]),[storm,setStorm]=useState(initialStorm),[metric,setMetric]=useState<Metric>('wind'),[mode,setMode]=useState<'analyze'|'collect'>('analyze'),[notice,setNotice]=useState('');
  const [collectionName,setCollectionName]=useState('FIELD OBSERVATIONS'),[rows,setRows]=useState<TrackPoint[]>([]),[obs,setObs]=useState<Observation>(EMPTY);const fileRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{try{const raw=localStorage.getItem('nari-lab-datasets');if(raw)setSaved(JSON.parse(raw))}catch{}},[]);
  const persist=(next:Storm[])=>{setSaved(next);try{localStorage.setItem('nari-lab-datasets',JSON.stringify(next.slice(-12)))}catch{}};
  const all=[...storms,...saved];
  useEffect(()=>{if(initialStorm.id.startsWith('custom-'))setStorm(initialStorm)},[initialStorm]);
  const values=storm.track.map(x=>x[metric]),mean=values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length):0,peak=values.length?(metric==='pressure'?Math.min(...values):Math.max(...values)):0;
  const completeness=Math.round(storm.track.reduce((sum,p)=>sum+[p.lat,p.lon,p.wind,p.pressure,p.rain].filter(Number.isFinite).length,0)/(storm.track.length*5)*100);
  const exportData=(kind:'csv'|'json',source=storm)=>{const text=kind==='json'?JSON.stringify({name:source.name,provenance:source.basin,units:{hour:'h',lat:'degrees_north',lon:'degrees_east',wind:'kt',pressure:'hPa',rain:'mm'},track:source.track},null,2):'hour,latitude,longitude,wind_kt,pressure_hpa,rain_mm\n'+source.track.map(x=>`${x.hour},${x.lat},${x.lon},${x.wind},${x.pressure},${x.rain}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:kind==='json'?'application/json':'text/csv'}));a.download=`${source.name.toLowerCase().replace(/\s+/g,'-')}.${kind}`;a.click();URL.revokeObjectURL(a.href)};
  const importFile=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();let parsed:Record<string,unknown>[]=[];if(file.name.toLowerCase().endsWith('.json')){const json=JSON.parse(text);parsed=Array.isArray(json)?json:Array.isArray(json.track)?json.track:Array.isArray(json.storms)?json.storms:[]}else{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);const headers=csvCells(lines.shift()||'');parsed=lines.map(line=>Object.fromEntries(csvCells(line).map((v,i)=>[headers[i],v])))}const track=parsed.map(normalizeRow).filter((p):p is TrackPoint=>p!==null);if(track.length<2)throw new Error('No valid rows');const imported=importedStorm(file.name,track),next=[...saved.filter(s=>s.name!==imported.name),imported];persist(next);setStorm(imported);setMode('analyze');setNotice(`${track.length} validated records imported and saved on this device.`)}catch{setNotice('Import failed. Include hour, latitude, longitude, wind_kt, pressure_hpa and rain_mm columns.')}finally{e.target.value=''}};
  const addObservation=()=>{const point={...obs};const next=[...rows,point].sort((a,b)=>a.hour-b.hour);setRows(next);setObs(v=>({...v,hour:Math.max(...next.map(p=>p.hour))+6}));setNotice(`Observation +${point.hour}h added to the local collection.`)};
  const saveCollection=()=>{if(rows.length<2){setNotice('Add at least two observations before saving a dataset.');return}const dataset=importedStorm(collectionName,rows),next=[...saved,dataset];persist(next);setStorm(dataset);setMode('analyze');setNotice(`${rows.length} observations saved locally and ready for analysis.`)};
  const currentRows=mode==='collect'?rows:storm.track;
  return <section className="content-page data-page">
    <div className="page-intro row"><div><p className="eyebrow">OBSERVATION + ANALYSIS WORKSPACE</p><h1>Data Collection</h1><p>Bring your own track data, collect field observations, validate records, plot key variables, and export every result.</p></div><div className="data-actions"><input ref={fileRef} hidden type="file" accept=".csv,.json,text/csv,application/json" onChange={importFile}/><button className="primary-action" onClick={()=>fileRef.current?.click()}>↑ IMPORT CSV / JSON</button><button onClick={()=>exportData('csv',importedStorm('nari-template',[EMPTY,{...EMPTY,hour:6,lat:18.8,lon:131.7,wind:52,pressure:990,rain:135}]))}>↓ TEMPLATE</button></div></div>
    <div className="data-mode"><button className={mode==='analyze'?'active':''} onClick={()=>setMode('analyze')}>ANALYZE DATASET</button><button className={mode==='collect'?'active':''} onClick={()=>setMode('collect')}>COLLECT OBSERVATIONS</button><span>DEVICE-LOCAL · PRIVATE BY DEFAULT</span></div>
    {notice&&<div className="data-notice"><span>●</span>{notice}<button onClick={()=>setNotice('')}>×</button></div>}
    {mode==='analyze'?<>
      <div className="dataset-bar glass"><div><span>ACTIVE DATASET</span><select value={storm.id} onChange={e=>setStorm(all.find(s=>s.id===e.target.value)||storm)}>{all.map(s=><option value={s.id} key={s.id}>{s.name} · {s.year} · {s.track.length} records</option>)}</select></div><div className="quality"><span><i style={{width:`${completeness}%`}}/></span><b>{completeness}% COMPLETE</b></div><div className="dataset-export"><button onClick={()=>exportData('csv')}>↓ CSV</button><button onClick={()=>exportData('json')}>↓ JSON</button></div></div>
      <div className="analytics-kpis"><article><span>VALID RECORDS</span><b>{storm.track.length}<small> rows</small></b></article><article><span>PEAK {metric.toUpperCase()}</span><b>{peak}<small>{metric==='wind'?' kt':metric==='pressure'?' hPa':' mm'}</small></b></article><article><span>PERIOD MEAN</span><b>{mean}<small>{metric==='wind'?' kt':metric==='pressure'?' hPa':' mm'}</small></b></article><article><span>TIME COVERAGE</span><b>{storm.track.at(-1)?.hour??0}<small> hours</small></b></article></div>
      <div className="analysis-grid data-analysis-grid"><article className="chart-card glass"><div className="chart-head"><div><p className="eyebrow">VALIDATED TIME SERIES</p><h2>{metric==='wind'?'Maximum sustained wind':metric==='pressure'?'Minimum central pressure':'Rainfall accumulation rate'}</h2></div><div className="segmented">{(['wind','pressure','rain'] as const).map(m=><button key={m} className={metric===m?'active':''} onClick={()=>setMetric(m)}>{m.toUpperCase()}</button>)}</div></div><StormChart storm={storm} metric={metric}/></article>
        <aside className="data-summary glass"><p className="eyebrow">DATA HEALTH</p><h2>{completeness===100?'Analysis ready':'Review recommended'}</h2><ul><li><span>Coordinates</span><b>{storm.track.every(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon))?'PASS':'CHECK'}</b></li><li><span>Pressure range</span><b>{Math.min(...storm.track.map(p=>p.pressure))}–{Math.max(...storm.track.map(p=>p.pressure))} hPa</b></li><li><span>Wind range</span><b>{Math.min(...storm.track.map(p=>p.wind))}–{Math.max(...storm.track.map(p=>p.wind))} kt</b></li><li><span>Time ordering</span><b>PASS</b></li></ul><p className="local-note">Imported data remains in your browser on this device. Nothing is transmitted to a server.</p></aside></div>
    </>:<>
      <div className="collector-grid"><section className="collector-form glass"><p className="eyebrow">MANUAL LOGGER</p><h2>Add an observation</h2><label className="collector-name"><span>DATASET NAME</span><input value={collectionName} onChange={e=>setCollectionName(e.target.value)}/></label><div className="observation-grid">{([['hour','FORECAST HOUR','h'],['lat','LATITUDE','°N'],['lon','LONGITUDE','°E'],['wind','WIND','kt'],['pressure','PRESSURE','hPa'],['rain','RAINFALL','mm']] as [keyof Observation,string,string][]).map(([key,label,unit])=><label key={key}><span>{label}</span><div><input type="number" value={obs[key]} onChange={e=>setObs({...obs,[key]:+e.target.value})}/><b>{unit}</b></div></label>)}</div><button className="primary-action wide" onClick={addObservation}>＋ ADD OBSERVATION</button><button className="save-dataset" disabled={rows.length<2} onClick={saveCollection}>SAVE DATASET + ANALYZE →</button></section>
        <section className="collection-status glass"><div className="collection-ring"><b>{rows.length}</b><span>RECORDS</span></div><h3>{rows.length<2?'Waiting for observations':`${rows.length} records staged`}</h3><p>Records are validated for geographic and meteorological ranges when imported. Manual observations can be edited by removing and re-adding them.</p><button onClick={()=>setRows([])} disabled={!rows.length}>CLEAR COLLECTION</button></section></div>
    </>}
    <section className="records glass"><div className="records-head"><div><p className="eyebrow">RECORD INSPECTOR</p><h2>{currentRows.length} observations</h2></div><span>SCHEMA v1 · SI-COMPATIBLE FIELDS</span></div><div className="table-scroll"><table><thead><tr><th>HOUR</th><th>LATITUDE</th><th>LONGITUDE</th><th>WIND (KT)</th><th>PRESSURE (HPA)</th><th>RAIN (MM)</th><th>QC</th></tr></thead><tbody>{currentRows.map((p,i)=><tr key={`${p.hour}-${i}`}><td>+{p.hour}</td><td>{p.lat.toFixed(1)}°</td><td>{p.lon.toFixed(1)}°</td><td><b>{p.wind}</b></td><td>{p.pressure}</td><td>{p.rain}</td><td><span className="qc">VALID</span></td></tr>)}</tbody></table>{!currentRows.length&&<div className="empty-table">No observations yet. Add the first record above.</div>}</div></section>
  </section>;
}
